#!/bin/bash

[ ! -d $HOME/.config ] && mkdir -pv $HOME/.config
[ ! -d $HOME/.local/share/fonts ] && mkdir -pv $HOME/.local/share/fonts

[ -d $HOME/.config/dunst ] && rm -rfv $HOME/.config/dunst ; cp -rv dunst $HOME/.config || cp -rv dunst $HOME/.config
[ -d $HOME/.config/nvim ] && rm -rfv $HOME/.config/nvim ; cp -rv nvim $HOME/.config || cp -rv nvim $HOME/.config
[ -d $HOME/.config/sx ] && rm -rfv $HOME/.config/sx ; cp -rv sx $HOME/.config || cp -rv sx $HOME/.config
[ -d $HOME/.config/sxhkd ] && rm -rfv $HOME/.config/sxhkd ; cp -rv sxhkd $HOME/.config || cp -rv sxhkd $HOME/.config
[ -f $HOME/.yashrc ] && rm -rfv $HOME/.yashrc && cp -v yashrc $HOME/.yashrc || cp -v yashrc $HOME/.yashrc

cp -v fonts/jetbrains-mono/* $HOME/.local/share/fonts

suckless() { 
	[ ! -d $HOME/.local/src ] && mkdir -pv $HOME/.local/src
	
	[ -d $HOME/.local/src/dwm ] && rm -rfv $HOME/.local/src/dwm
	[ -d $HOME/.local/src/dmenu ] && rm -rfv $HOME/.local/src/dmenu
	[ -d $HOME/.local/src/st ] && rm -rfv $HOME/.local/src/st

	cd $HOME/.local/src &&

	git clone https://github.com/synthun/dwm &&
	git clone https://github.com/synthun/dmenu &&
	git clone https://github.com/synthun/st &&

	echo "root privelages are required to compile"
	cd dwm ; su -c 'make clean install' && cd .. || exit
	cd dmenu ; su -c 'make clean install' && cd .. || exit
	cd st ; su -c 'make clean install' && cd .. || exit
}

read -p "install suckless? (y/n): "
case $REPLY in
	y) suckless;;
	n) exit
esac
