#!/bin/sh

[ ! -d $HOME/.config ] && mkdir -pv $HOME/.config
[ ! -d $HOME/.local/share/fonts ] && mkdir -pv $HOME/.local/share/fonts
[ ! -d $HOME/.local/src ] && mkdir -pv $HOME/.local/src

[ -d $HOME/.config/dunst ] && rm -rfv $HOME/.config/dunst ; cp -rv dunst $HOME/.config || cp -rv dunst $HOME/.config
[ -d $HOME/.config/sx ] && rm -rfv $HOME/.config/sx ; cp -rv sx $HOME/.config || cp -rv sx $HOME/.config
[ -d $HOME/.config/sxhkd ] && rm -rfv $HOME/.config/sxhkd ; cp -rv sxhkd $HOME/.config || cp -rv sxhkd $HOME/.config
[ -f $HOME/.zshrc ] && rm -rfv $HOME/.zshrc && cp -v zshrc $HOME/.zshrc || cp -v zshrc $HOME/.zshrc

cp -v fonts/jetbrains-mono/* $HOME/.local/share/fonts
